### ISSUE TITLE
Run tests in the same process as server

### ISSUE THREAD

**Issue by DavertMik** [Codeception/codepress#1]
Don't start a new process when executing tests. Execute tests inside a server.
Replace `child_process` with native test execution.

**Comment by DavertMik** [comment]
Resolved in #12

**Comment by hubidu** [comment]
I could not figure out what exactly the problem is when running the tests in process. They are obviously running but no events are fired which indicates that the helper is not loaded/executed on the repeated runs. The websocket connection is fine.
It must have to do with the singleton instance since when you do not cache the instance but instead create a new one every time, then events are fired also for repeated runs. However in this case it seems that every time an additional instance of the helper is added and therefore multiple events of the same type are fired.
In any case it works fine when running out of process therefore I restored the original route and put your code in an additional /run-ips route. We can switch between routes changing the url in TestRun.vue:94.

**Comment by hubidu** [comment]
@DavertMik Could you please take a look again? See my above comment. The problem is not in the frontend/websockets. The problem is still that the container/config/codecept instance can not be used multiple times.
